### PR TITLE
Fix sending job to all devices

### LINKED ISSUE #20: Job to all devices not possible
I can only select 5-6 devices for a job. if I select more then i got an error on the ui, but no error in the log.

### PR DESCRIPTION
**Pull request by Fabio1988**
resolves #20 

Due to a restriction to length of a param in the url this caused an error (404 NOT FOUND)

### CODE REVIEW

File: packages/server/src/index.ts [hunk 1]
```diff
@@ -533,24 +533,26 @@ const routes = async (fastifyInstance: FastifyInstance) => {
...
       if (!job) {
         reply.code(404).send({ status: 'error', error: 'Job not found' });
-
         return;
       }
 
-      const devices: DeviceControlConnection[] = deviceIdsOrOrigins
+      // If deviceIdsOrOrigins is not set in URL params, use the value from the request body
+      const deviceIdsOrOriginsList =
+        deviceIdsOrOrigins !== undefined ? deviceIdsOrOrigins.split(',') : req.body.deviceIdsOrOrigins;
```
Comment (na-ji) [inline packages/server/src/index.ts]: Are you supporting both the URL params and the body because you didn't want to make a breaking change?

Comment (Fabio1988) [reply packages/server/src/index.ts]: exactly.. I changed the API call within Rotom client.. But some tools rely on the API, so I thought it would be nice to have it backward compatible

Comment (Fabio1988) [reply packages/server/src/index.ts]: would you prefer a new endpoint instead? of good?

File: package.json [hunk 2]
```diff
@@ -12,6 +12,7 @@
     "dev:server": "nx run server:dev",
     "lint": "nx run-many --target=lint --all",
     "start": "node dist/packages/server/main.js",
+    "test": "NODE_ENV=development NX_ENABLE_MOCKS=1 nx run-many --target=dev --all",
```
Comment (na-ji) [inline package.json]: You could rename it like this, since it doesn't really start automated test. 
```suggestion
    "dev:mock": "NODE_ENV=development NX_ENABLE_MOCKS=1 nx run-many --target=dev --all",
```

File: packages/client/src/app/jobs/executeJobModal.tsx [hunk 3]
```diff
@@ -15,19 +15,22 @@ export const ExecuteJobModal = ({ closeModal, devices, jobId }: ExecuteJobModalP
...
-        async (response) => {
-          if (response.status !== 200) {
-            throw new Error();
-          }
-
-          closeModal();
+      const promise = fetch(`/api/job/execute/${jobId}`, {
+        method: 'POST',
+        headers: {
+          'Content-Type': 'application/json', // Set the Content-Type header to application/json
```
Comment (na-ji) [inline packages/client/src/app/jobs/executeJobModal.tsx]: I'm not sure this comment is useful :)

**Review by na-ji — APPROVED** [review]
Thanks for finding the issue. 👍

**Review by na-ji — APPROVED** [review]
